In [1]:
import torch

data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [2]:
tensor = x_data
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([2, 2])
Datatype of tensor: torch.int64
Device tensor is stored on: cpu


In [16]:
tensor = x_data
tensor[:,1] = 0
print(tensor)
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(y1)
print(y2)

tensor([[1, 0, 3, 0],
        [1, 0, 0, 0]])
tensor([[10,  1],
        [ 1,  1]])
tensor([[10,  1],
        [ 1,  1]])
